version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./tesla_complete/backend:/app/tesla_complete/backend
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./tesla_complete/frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
